/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as ConsultationRouteImport } from './routes/consultation'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CybersecurityRouteImport } from './routes/cybersecurity'
import { Route as DownloadRouteImport } from './routes/download'
import { Route as EnrollRouteRouteImport } from './routes/enroll/route'
import { Route as ItServicesRouteImport } from './routes/it-services'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AcademyIndexRouteImport } from './routes/academy/index'
import { Route as AcademySchoolRouteImport } from './routes/academy/$school'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminArticlesRouteImport } from './routes/admin/articles'
import { Route as AdminDownloadsRouteImport } from './routes/admin/downloads'
import { Route as AdminEnrollmentsRouteImport } from './routes/admin/enrollments'
import { Route as AdminInquiriesRouteImport } from './routes/admin/inquiries'
import { Route as AdminPagesRouteImport } from './routes/admin/pages'
import { Route as AdminPaymentsRouteImport } from './routes/admin/payments'
import { Route as AdminProgramsRouteImport } from './routes/admin/programs'
import { Route as AdminServicesRouteImport } from './routes/admin/services'
import { Route as AdminSettingsRouteImport } from './routes/admin/settings'
import { Route as CybersecuritySlugRouteImport } from './routes/cybersecurity/$slug'
import { Route as EnrollIndexRouteImport } from './routes/enroll/index'
import { Route as EnrollPaidRouteImport } from './routes/enroll/paid'
import { Route as EnrollPayRouteImport } from './routes/enroll/pay'
import { Route as PagesSlugRouteImport } from './routes/pages/$slug'
import { Route as ResourcesIndexRouteImport } from './routes/resources/index'
import { Route as ResourcesSlugRouteImport } from './routes/resources/$slug'
import { Route as ServicesSlugRouteImport } from './routes/services/$slug'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsultationRoute = ConsultationRouteImport.update({
  id: '/consultation',
  path: '/consultation',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CybersecurityRoute = CybersecurityRouteImport.update({
  id: '/cybersecurity',
  path: '/cybersecurity',
  getParentRoute: () => rootRouteImport,
} as any)
const DownloadRoute = DownloadRouteImport.update({
  id: '/download',
  path: '/download',
  getParentRoute: () => rootRouteImport,
} as any)
const EnrollRouteRoute = EnrollRouteRouteImport.update({
  id: '/enroll',
  path: '/enroll',
  getParentRoute: () => rootRouteImport,
} as any)
const ItServicesRoute = ItServicesRouteImport.update({
  id: '/it-services',
  path: '/it-services',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademyIndexRoute = AcademyIndexRouteImport.update({
  id: '/academy/',
  path: '/academy/',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademySchoolRoute = AcademySchoolRouteImport.update({
  id: '/academy/$school',
  path: '/academy/$school',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminArticlesRoute = AdminArticlesRouteImport.update({
  id: '/articles',
  path: '/articles',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminDownloadsRoute = AdminDownloadsRouteImport.update({
  id: '/downloads',
  path: '/downloads',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminEnrollmentsRoute = AdminEnrollmentsRouteImport.update({
  id: '/enrollments',
  path: '/enrollments',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminInquiriesRoute = AdminInquiriesRouteImport.update({
  id: '/inquiries',
  path: '/inquiries',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminPagesRoute = AdminPagesRouteImport.update({
  id: '/pages',
  path: '/pages',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminPaymentsRoute = AdminPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminProgramsRoute = AdminProgramsRouteImport.update({
  id: '/programs',
  path: '/programs',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminServicesRoute = AdminServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRouteRoute,
} as any)
const CybersecuritySlugRoute = CybersecuritySlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => CybersecurityRoute,
} as any)
const EnrollIndexRoute = EnrollIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EnrollRouteRoute,
} as any)
const EnrollPaidRoute = EnrollPaidRouteImport.update({
  id: '/paid',
  path: '/paid',
  getParentRoute: () => EnrollRouteRoute,
} as any)
const EnrollPayRoute = EnrollPayRouteImport.update({
  id: '/pay',
  path: '/pay',
  getParentRoute: () => EnrollRouteRoute,
} as any)
const PagesSlugRoute = PagesSlugRouteImport.update({
  id: '/pages/$slug',
  path: '/pages/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesIndexRoute = ResourcesIndexRouteImport.update({
  id: '/resources/',
  path: '/resources/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesSlugRoute = ResourcesSlugRouteImport.update({
  id: '/resources/$slug',
  path: '/resources/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesSlugRoute = ServicesSlugRouteImport.update({
  id: '/services/$slug',
  path: '/services/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/enroll': typeof EnrollRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/consultation': typeof ConsultationRoute
  '/contact': typeof ContactRoute
  '/cybersecurity': typeof CybersecurityRouteWithChildren
  '/download': typeof DownloadRoute
  '/it-services': typeof ItServicesRoute
  '/login': typeof LoginRoute
  '/academy/$school': typeof AcademySchoolRoute
  '/admin/articles': typeof AdminArticlesRoute
  '/admin/downloads': typeof AdminDownloadsRoute
  '/admin/enrollments': typeof AdminEnrollmentsRoute
  '/admin/inquiries': typeof AdminInquiriesRoute
  '/admin/pages': typeof AdminPagesRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/programs': typeof AdminProgramsRoute
  '/admin/services': typeof AdminServicesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/cybersecurity/$slug': typeof CybersecuritySlugRoute
  '/enroll/paid': typeof EnrollPaidRoute
  '/enroll/pay': typeof EnrollPayRoute
  '/pages/$slug': typeof PagesSlugRoute
  '/resources/$slug': typeof ResourcesSlugRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/academy/': typeof AcademyIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/enroll/': typeof EnrollIndexRoute
  '/resources/': typeof ResourcesIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/consultation': typeof ConsultationRoute
  '/contact': typeof ContactRoute
  '/cybersecurity': typeof CybersecurityRouteWithChildren
  '/download': typeof DownloadRoute
  '/it-services': typeof ItServicesRoute
  '/login': typeof LoginRoute
  '/academy/$school': typeof AcademySchoolRoute
  '/admin/articles': typeof AdminArticlesRoute
  '/admin/downloads': typeof AdminDownloadsRoute
  '/admin/enrollments': typeof AdminEnrollmentsRoute
  '/admin/inquiries': typeof AdminInquiriesRoute
  '/admin/pages': typeof AdminPagesRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/programs': typeof AdminProgramsRoute
  '/admin/services': typeof AdminServicesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/cybersecurity/$slug': typeof CybersecuritySlugRoute
  '/enroll/paid': typeof EnrollPaidRoute
  '/enroll/pay': typeof EnrollPayRoute
  '/pages/$slug': typeof PagesSlugRoute
  '/resources/$slug': typeof ResourcesSlugRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/academy': typeof AcademyIndexRoute
  '/admin': typeof AdminIndexRoute
  '/enroll': typeof EnrollIndexRoute
  '/resources': typeof ResourcesIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/enroll': typeof EnrollRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/consultation': typeof ConsultationRoute
  '/contact': typeof ContactRoute
  '/cybersecurity': typeof CybersecurityRouteWithChildren
  '/download': typeof DownloadRoute
  '/it-services': typeof ItServicesRoute
  '/login': typeof LoginRoute
  '/academy/$school': typeof AcademySchoolRoute
  '/admin/articles': typeof AdminArticlesRoute
  '/admin/downloads': typeof AdminDownloadsRoute
  '/admin/enrollments': typeof AdminEnrollmentsRoute
  '/admin/inquiries': typeof AdminInquiriesRoute
  '/admin/pages': typeof AdminPagesRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/programs': typeof AdminProgramsRoute
  '/admin/services': typeof AdminServicesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/cybersecurity/$slug': typeof CybersecuritySlugRoute
  '/enroll/paid': typeof EnrollPaidRoute
  '/enroll/pay': typeof EnrollPayRoute
  '/pages/$slug': typeof PagesSlugRoute
  '/resources/$slug': typeof ResourcesSlugRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/academy/': typeof AcademyIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/enroll/': typeof EnrollIndexRoute
  '/resources/': typeof ResourcesIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/enroll'
    | '/about'
    | '/consultation'
    | '/contact'
    | '/cybersecurity'
    | '/download'
    | '/it-services'
    | '/login'
    | '/academy/$school'
    | '/admin/articles'
    | '/admin/downloads'
    | '/admin/enrollments'
    | '/admin/inquiries'
    | '/admin/pages'
    | '/admin/payments'
    | '/admin/programs'
    | '/admin/services'
    | '/admin/settings'
    | '/cybersecurity/$slug'
    | '/enroll/paid'
    | '/enroll/pay'
    | '/pages/$slug'
    | '/resources/$slug'
    | '/services/$slug'
    | '/academy/'
    | '/admin/'
    | '/enroll/'
    | '/resources/'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/consultation'
    | '/contact'
    | '/cybersecurity'
    | '/download'
    | '/it-services'
    | '/login'
    | '/academy/$school'
    | '/admin/articles'
    | '/admin/downloads'
    | '/admin/enrollments'
    | '/admin/inquiries'
    | '/admin/pages'
    | '/admin/payments'
    | '/admin/programs'
    | '/admin/services'
    | '/admin/settings'
    | '/cybersecurity/$slug'
    | '/enroll/paid'
    | '/enroll/pay'
    | '/pages/$slug'
    | '/resources/$slug'
    | '/services/$slug'
    | '/academy'
    | '/admin'
    | '/enroll'
    | '/resources'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/enroll'
    | '/about'
    | '/consultation'
    | '/contact'
    | '/cybersecurity'
    | '/download'
    | '/it-services'
    | '/login'
    | '/academy/$school'
    | '/admin/articles'
    | '/admin/downloads'
    | '/admin/enrollments'
    | '/admin/inquiries'
    | '/admin/pages'
    | '/admin/payments'
    | '/admin/programs'
    | '/admin/services'
    | '/admin/settings'
    | '/cybersecurity/$slug'
    | '/enroll/paid'
    | '/enroll/pay'
    | '/pages/$slug'
    | '/resources/$slug'
    | '/services/$slug'
    | '/academy/'
    | '/admin/'
    | '/enroll/'
    | '/resources/'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  EnrollRouteRoute: typeof EnrollRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  ConsultationRoute: typeof ConsultationRoute
  ContactRoute: typeof ContactRoute
  CybersecurityRoute: typeof CybersecurityRouteWithChildren
  DownloadRoute: typeof DownloadRoute
  ItServicesRoute: typeof ItServicesRoute
  LoginRoute: typeof LoginRoute
  AcademySchoolRoute: typeof AcademySchoolRoute
  PagesSlugRoute: typeof PagesSlugRoute
  ResourcesSlugRoute: typeof ResourcesSlugRoute
  ServicesSlugRoute: typeof ServicesSlugRoute
  AcademyIndexRoute: typeof AcademyIndexRoute
  ResourcesIndexRoute: typeof ResourcesIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consultation': {
      id: '/consultation'
      path: '/consultation'
      fullPath: '/consultation'
      preLoaderRoute: typeof ConsultationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cybersecurity': {
      id: '/cybersecurity'
      path: '/cybersecurity'
      fullPath: '/cybersecurity'
      preLoaderRoute: typeof CybersecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/download': {
      id: '/download'
      path: '/download'
      fullPath: '/download'
      preLoaderRoute: typeof DownloadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/enroll': {
      id: '/enroll'
      path: '/enroll'
      fullPath: '/enroll'
      preLoaderRoute: typeof EnrollRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/it-services': {
      id: '/it-services'
      path: '/it-services'
      fullPath: '/it-services'
      preLoaderRoute: typeof ItServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academy/': {
      id: '/academy/'
      path: '/academy'
      fullPath: '/academy/'
      preLoaderRoute: typeof AcademyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academy/$school': {
      id: '/academy/$school'
      path: '/academy/$school'
      fullPath: '/academy/$school'
      preLoaderRoute: typeof AcademySchoolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/articles': {
      id: '/admin/articles'
      path: '/articles'
      fullPath: '/admin/articles'
      preLoaderRoute: typeof AdminArticlesRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/downloads': {
      id: '/admin/downloads'
      path: '/downloads'
      fullPath: '/admin/downloads'
      preLoaderRoute: typeof AdminDownloadsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/enrollments': {
      id: '/admin/enrollments'
      path: '/enrollments'
      fullPath: '/admin/enrollments'
      preLoaderRoute: typeof AdminEnrollmentsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/inquiries': {
      id: '/admin/inquiries'
      path: '/inquiries'
      fullPath: '/admin/inquiries'
      preLoaderRoute: typeof AdminInquiriesRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/pages': {
      id: '/admin/pages'
      path: '/pages'
      fullPath: '/admin/pages'
      preLoaderRoute: typeof AdminPagesRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/payments': {
      id: '/admin/payments'
      path: '/payments'
      fullPath: '/admin/payments'
      preLoaderRoute: typeof AdminPaymentsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/programs': {
      id: '/admin/programs'
      path: '/programs'
      fullPath: '/admin/programs'
      preLoaderRoute: typeof AdminProgramsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/services': {
      id: '/admin/services'
      path: '/services'
      fullPath: '/admin/services'
      preLoaderRoute: typeof AdminServicesRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/cybersecurity/$slug': {
      id: '/cybersecurity/$slug'
      path: '/$slug'
      fullPath: '/cybersecurity/$slug'
      preLoaderRoute: typeof CybersecuritySlugRouteImport
      parentRoute: typeof CybersecurityRoute
    }
    '/enroll/': {
      id: '/enroll/'
      path: '/'
      fullPath: '/enroll/'
      preLoaderRoute: typeof EnrollIndexRouteImport
      parentRoute: typeof EnrollRouteRoute
    }
    '/enroll/paid': {
      id: '/enroll/paid'
      path: '/paid'
      fullPath: '/enroll/paid'
      preLoaderRoute: typeof EnrollPaidRouteImport
      parentRoute: typeof EnrollRouteRoute
    }
    '/enroll/pay': {
      id: '/enroll/pay'
      path: '/pay'
      fullPath: '/enroll/pay'
      preLoaderRoute: typeof EnrollPayRouteImport
      parentRoute: typeof EnrollRouteRoute
    }
    '/pages/$slug': {
      id: '/pages/$slug'
      path: '/pages/$slug'
      fullPath: '/pages/$slug'
      preLoaderRoute: typeof PagesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources/': {
      id: '/resources/'
      path: '/resources'
      fullPath: '/resources/'
      preLoaderRoute: typeof ResourcesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources/$slug': {
      id: '/resources/$slug'
      path: '/resources/$slug'
      fullPath: '/resources/$slug'
      preLoaderRoute: typeof ResourcesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/$slug': {
      id: '/services/$slug'
      path: '/services/$slug'
      fullPath: '/services/$slug'
      preLoaderRoute: typeof ServicesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteRouteChildren {
  AdminArticlesRoute: typeof AdminArticlesRoute
  AdminDownloadsRoute: typeof AdminDownloadsRoute
  AdminEnrollmentsRoute: typeof AdminEnrollmentsRoute
  AdminInquiriesRoute: typeof AdminInquiriesRoute
  AdminPagesRoute: typeof AdminPagesRoute
  AdminPaymentsRoute: typeof AdminPaymentsRoute
  AdminProgramsRoute: typeof AdminProgramsRoute
  AdminServicesRoute: typeof AdminServicesRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminArticlesRoute: AdminArticlesRoute,
  AdminDownloadsRoute: AdminDownloadsRoute,
  AdminEnrollmentsRoute: AdminEnrollmentsRoute,
  AdminInquiriesRoute: AdminInquiriesRoute,
  AdminPagesRoute: AdminPagesRoute,
  AdminPaymentsRoute: AdminPaymentsRoute,
  AdminProgramsRoute: AdminProgramsRoute,
  AdminServicesRoute: AdminServicesRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface EnrollRouteRouteChildren {
  EnrollPaidRoute: typeof EnrollPaidRoute
  EnrollPayRoute: typeof EnrollPayRoute
  EnrollIndexRoute: typeof EnrollIndexRoute
}

const EnrollRouteRouteChildren: EnrollRouteRouteChildren = {
  EnrollPaidRoute: EnrollPaidRoute,
  EnrollPayRoute: EnrollPayRoute,
  EnrollIndexRoute: EnrollIndexRoute,
}

const EnrollRouteRouteWithChildren = EnrollRouteRoute._addFileChildren(
  EnrollRouteRouteChildren,
)

interface CybersecurityRouteChildren {
  CybersecuritySlugRoute: typeof CybersecuritySlugRoute
}

const CybersecurityRouteChildren: CybersecurityRouteChildren = {
  CybersecuritySlugRoute: CybersecuritySlugRoute,
}

const CybersecurityRouteWithChildren = CybersecurityRoute._addFileChildren(
  CybersecurityRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  EnrollRouteRoute: EnrollRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  ConsultationRoute: ConsultationRoute,
  ContactRoute: ContactRoute,
  CybersecurityRoute: CybersecurityRouteWithChildren,
  DownloadRoute: DownloadRoute,
  ItServicesRoute: ItServicesRoute,
  LoginRoute: LoginRoute,
  AcademySchoolRoute: AcademySchoolRoute,
  PagesSlugRoute: PagesSlugRoute,
  ResourcesSlugRoute: ResourcesSlugRoute,
  ServicesSlugRoute: ServicesSlugRoute,
  AcademyIndexRoute: AcademyIndexRoute,
  ResourcesIndexRoute: ResourcesIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
